### ISSUE TITLE
Can't see which tab has focus

### ISSUE THREAD

**Issue by demolitions** [FedeDP/ncursesFM#1]
When you open a second tab, you lose track very fast about which one has the focus.
It actually takes a keypress to see the arrow moving on the focused one, but it's a bit confusing.

Maybe a different color for the arrow on the focused one would help.

**Comment by FedeDP** [comment]
Yes, i was thinking that green color is the right choice.
Thanks for the report!

**Comment by ghost** [comment]
Food for thought: Color-based indications might prove difficult for the colorblind.

**Comment by FedeDP** [comment]
You're right...have you got any suggestion about this issue?

**Comment by FedeDP** [comment]
By the way i was reworking this to make it more evident: http://postimg.org/image/7af4i6b41/full/ (borders will be red for fast browse mode, following cursor colors)
