### ISSUE TITLE
Some improvements concerning functions

### ISSUE THREAD

**Issue by JujuLand** [FedeDP/ncursesFM#10]
1) The possibility to copy the complete path when using function 'i' (not automatically, but using another key , c for exemple)
2) Have the possility to choose between open or extract for an archive, by using a different key:
Enter opens using xgd-open, and another key (as 'x' is already used) to extract it. Because when extracting like it's now implemented, we have no possible choice for the target folder where to extract.

A+

**Comment by JujuLand** [comment]
If have open another request:
https://github.com/FedeDP/ncursesFM/issues/10
A+

**Comment by JujuLand** [comment]
I can't use 'j'. I have e message: 'You need w3mimgdisplay from w3m to preview images'
I have w3m installed
ii  w3m  0.5.3-5ubuntu1.1     WWW browsable pager with excellent tables/frames support
What is the needed version ?

If I understand, the only way to be able to change the default conf location is to build again ?
Yes ?
In this case, to avoid to build, what basic users aren't often unable to do, why not to always use /etc/default/, but having a field which is first read by ncursesFM to know the wanted conf file.
Coupling that functionnality with the possibility to decode $HOME, it will allow to have for all users a personal conf file.
Exemple:
# personal ncursesFM.conf location 
# personal_conf=$HOME/

Alain will then read /home/alain/ncursesFM.conf, and Beatrice /home/beatrice/ncursesFM.conf
;)

A+

**Comment by FedeDP** [comment]
I'll go in order:
1) i can't do that: ncursesFM doesn't know if user has a clipoard manager/if it is run from a tty, from wayland or whatelse...
2) i can do that, sure!
3) on ubuntu w3m image previewer is splitted, install w3m-img
4) Nope: at build time you can specify a different CONFDIR, but $USERHOME/.config/ncursesFM.conf will always be read, if present. If it is present, global conf file is not even read. (probably i should make user conf override default conf, i'll look into that)

**Comment by JujuLand** [comment]
1)  :(
2)  :)
3) Crash the program and the console. But what is the purpose of a such function ?
4) You're telling that the conf files are read in this order:
.   a) the one if CONDIR
.   b) the one in .config
.   c) the one in default
Right ?
For now doesn't work, but it perhaps not done for now ?

**Comment by FedeDP** [comment]
3) it was a feature requested and i added it. It works fine on xterm and urxvt, but i only tested with default configurations.
Very strange that it crashes. What terminal emulator are you using?
4) i've pushed right now a small commit with log improvements and conf file reading improvements.
Btw it reads: 
- global CONFDIR/ncursesFM.conf (normally located at /etc/default/)
- $HOME/.config/ncursesFM.conf
  user config will override global config.

**Comment by JujuLand** [comment]
3) ii  gnome-terminal  3.4.1.1-0ubuntu1 GNOME terminal emulator application
.    a) I Choose an image (a jpg)
.    b) I hit 'j' => it opens a tab with the filename as title, and nothing appears
.    c) I hit 'down' then'Esc'

![crash](https://cloud.githubusercontent.com/assets/5039517/15578321/ed612d58-2357-11e6-923d-aab1bc71bb83.png)

.

**Comment by JujuLand** [comment]
local conf works right.
Thanks
A+

**Comment by JujuLand** [comment]
Locally opening an xterm, it crashes too.
Now, I suppose that it must be use whent running an xterm console connected to an host.
Am-I right ?
I never use and know how an xterm connexion is made, even I know it exists.
I daily use ssh connexion with -X param which allows to open distant graphic programs, and in this case I think it's not necessary to use 'j'
A+

**Comment by FedeDP** [comment]
Yes, its usecases are quite restricted indeed.
Obviously i cannot reproduce that crash...i'll try on a docker image and see if i'm able to reproduce.

**Comment by JujuLand** [comment]
Well, to avoid crash, I will remove w3m-img, and no more problem ;)

A+

**Comment by FedeDP** [comment]
I cannot test it with docker because i constrained image previewer to x sessions (the script needs an X environment).
I'll probably wait on some other users responses on image previewer (here https://github.com/FedeDP/ncursesFM/issues/6).

**Comment by FedeDP** [comment]
Pushed right now.
Use 'z' to extract archives. You'll have to select them before. But you gained the possibility to extract more archives at the same time :) 

Btw i found some small issues i'd like to fix before merging into master (and before starting to work at internationalization), so you'll have to wait translating my strings :D

**Comment by JujuLand** [comment]
Nice, it works :)
ok
A+
