### ISSUE TITLE
Backspace should make you go down a directory

### ISSUE THREAD

**Issue by faissaloo** [FedeDP/ncursesFM#13]
I don't want to have to type ".." or scroll all the way up to go down, it's unintuitive.

**Comment by FedeDP** [comment]
You're right! I'll adress this issue!
Btw you can use PG UP to go back to first file on top(that in case of default sorting, will be "..").
I'll add backspace support tomorrow (i won't be at home until tomorrow)!
Thanks for your time :)

**Comment by FedeDP** [comment]
Fixed in 3e246b0741bc6ae8a027d676fe8a431d9bbbaca1
