### ISSUE TITLE
Error compiling under Xubuntu 16.04

### ISSUE THREAD

**Issue by JujuLand** [FedeDP/ncursesFM#19]
Hi,

after having installed the required packets, I have this error:

annie@xubuntu-IMEDIA:/opt/TuxPrograms/trunks/ncurseFM$ make
fm.c: In function \u2018recursive_copy\u2019:
fm.c:408:13: error: \u2018len\u2019 undeclared (first use in this function)
             len = read(fd_from, buff, sizeof(buff));
             ^
fm.c:408:13: note: each undeclared identifier is reported only once for each function it appears in
makefile:93 : la recette pour la cible « objects » a échouée
make: *** [objects] Erreur 1

Where do I failed ?

Thanks
A+

**Comment by FedeDP** [comment]
Thanks for reporting this issue.
I found the error and will fix as soon as possible :)
