### ISSUE TITLE
How to activate locale translation .

### ISSUE THREAD

**Issue by JujuLand** [FedeDP/ncursesFM#20]
Hi, I have now build v3.1 with success, and I have created fr.po which has been compiled as fr.mo, but I don't find haw to activate my locale.

I have tried to modify something in /etc/default/ncursesFM.conf, but it doesn't seem to do something.

Thanks
A+

**Comment by JujuLand** [comment]
Herei s fr.po
[fr.po.zip](https://github.com/FedeDP/ncursesFM/files/1310682/fr.po.zip)

**Comment by FedeDP** [comment]
It automatically uses language from your system; can you paste here output of "echo $LANG" ?
Btw thanks for translation file! I will add it to repo as soon as i go back home :)

PS: have you installed the .mo file? Ie: you should add fr.po file inside msg/ folder, than issue a "make" and finally "sudo make install"

**Comment by JujuLand** [comment]
ok, I understand.
My LANG is fr_FR.UTF8, so I must rename fr.po to fr_FR.po.
Right ?

A+

**Comment by FedeDP** [comment]
No, it is enough to leave it fr.po.

**Comment by JujuLand** [comment]
I had forgotten to install, that was the reason.
I have renamed it, and iit works too.

Thanks
A+

**Comment by FedeDP** [comment]
Thank you for taking the time to translate ncursesFM! I'll obviously add you to translators' list (https://github.com/FedeDP/ncursesFM/wiki/I18n#translators).
Thanks again!

**Comment by JujuLand** [comment]
I found a typo in your pot:
msgid "remove all user bookmakrs."

and one in mine:
msgstr "chrcher un fichier"
instead of "chercher un fichier"

A+

**Comment by FedeDP** [comment]
Thanks, i will fix it...or you can! Feel free to open a Pull Request to upload your translation and fix "bookmakrs" string (you should look for that typo in src/string_constants.c and in every .po file) if you are willing to.

**Comment by JujuLand** [comment]
As I don't know how to use pull, I prefer send you an archive

A+
[po-files.tar.gz](https://github.com/FedeDP/ncursesFM/files/1311223/po-files.tar.gz)

**Comment by FedeDP** [comment]
Thank you very much!
Your changes are now in master. Can you please rebuild ncursesFM from git and let me know if french lang works fine? 
Thank you!

EDIT: https://github.com/FedeDP/ncursesFM/wiki/I18n#translators :)

**Comment by FedeDP** [comment]
I was able to properly test french language and it works fine.
Again, thank you for your time! If you have any idea/suggestion/feature request, feel free to open any issue!
