### ISSUE TITLE
allow for easy custom line drawing art

### ISSUE THREAD

**Issue by phavx** [FedeDP/ncursesFM#3]
As you requested [here on reddit](https://www.reddit.com/r/linux/comments/4i4bm3/a_new_ncurses_filemanager_for_linux/d2v2gc2), this is a wish to make it easily configurable what characters should be used to draw lines and seperators.

While the current (+,-,|) works, some people would surely prefer something more fancy like ASCCI blocks or similar.

**Comment by FedeDP** [comment]
Hi! Thanks for your time!
Should be fixed in b9f8c3b65264d32a7c39a42c7c62cba350d70a21. 
Let me know if it is good enough for you :)

**Comment by phavx** [comment]
Looking good and thanks for the very fast service. On a further look, I noticed the "->" selector, would be nice if that one too would be made configurable.

**Comment by FedeDP** [comment]
Why not? :) I'm gonna make it asap!
Thanks for your ideas!

**Comment by FedeDP** [comment]
I made cursor chars customizables too in latest commit. 
Again, thanks!

**Comment by phavx** [comment]
Great work, thanks again for the very fast response. Now off into the weekend, a new toy to play with :)
