### ISSUE TITLE
Use some po/mo file for help zone translation

### ISSUE THREAD

**Issue by JujuLand** [FedeDP/ncursesFM#9]
Just about help zone.
Could it be apart of c source to allow easily to translate it, without having to modify code ?
Perhaps by using po/mo file ?

Thanks
A+

**Comment by FedeDP** [comment]
Thanks again for your time! 
I'll look into this as soon as i figure out how to properly fix unicode support :)

**Comment by FedeDP** [comment]
I just pushed an internationalized version of ncursesFM.  
To translate strings, go into msg folder, copy ncursesFM.pot into $your_lang.po, and add your translated strings in "msgstr" line for every string. (have a look at "it.po" in case you're unsure!)
In your case it should be:
$ cd msg
$ cp ncursesFM.pot fr.po  
edit fr.po.

To test your strings before submitting your changes to me, i added a local target to makefile, that will build with "CONFDIR=$current_dir BINDIR=$current_dir LOCALEDIR=$current_dir".
So, 
$ make local
$ ./ncursesFM
then check your translated strings with no need to install ncursesFM system-wide ;)
When you're ready, remove the "fuzzy" line (near the top) from the .po file, and check heading (TRANSLATOR, PO-revision-date, etc etc; again, have a look at it.po if you're unsure), then finally submit your changes to me (via paste service or pull request, as you're more comfortable!)

**Comment by FedeDP** [comment]
Mmh it seems my makefile install target for i18n files is wrong. Well for your testing it won't change anything (make local works fine), i'll fix it system wide asap!

**Comment by JujuLand** [comment]
.      I just pushed an internationalized version of ncursesFM.

Needed to start from scrach, probably because of old checkout

```
  To translate strings, go into msg folder, copy ncursesFM.pot into $your_lang.po, and add your
   translated strings in "msgstr" line for every string. (have a look at "it.po" in case you're
   unsure!)
    In your case it should be:
    $ cd msg
    $ cp ncursesFM.pot fr.po
    $ edit fr.po.
```

There is a problem with your po(t) file.
What is wrong:
msgstr
What is good:
msgstr ""
opening po file with poedit shows empty file due to missing ""

```
  To test your strings before submitting your changes to me, i added a local target to makefile, that 
  will build with
    "CONFDIR=$current_dir BINDIR=$current_dir
    LOCALEDIR=$current_dir".
    So, 
    `$ cd ..`
    $ make local
    $ ./ncursesFM
    then check your translated strings with no need to install
    ncursesFM system-wide ;)
```

ok, that works

```
    When you're ready, remove the "fuzzy" line (near the top) from the .po file, and check 
    intestation 
```

What is the purpose of .fuzzy ?
Using poedit remove automatically the line
intestation = installation ?

```
  (TRANSLATOR, PO-revision-date, etc etc; again, have a look at it.po if you're unsure),
```

no problem with these tags

```
   then finally submit your changes to me (via paste service or pull request, as you're more 
   comfortable!)
```

ok, I will do it

Just a question, about shortcuts, and just perhaps about help content:

a) s -> see stat about files in current folder
not necessary, as it displays even changing the folder

b) v/x -> paste/cut
with v     i: indicates copied, not pasted
with x     i: indicates moved, not cut
This is for info, but more, I don't see where and how is copied, or moved the selection.

A+

**Comment by FedeDP** [comment]
1) i used a normal text editor, so i haven't been warned about msgstr "" . I'll fix it in ncursesFM.pot, thanks!
2) I meant heading (intestation does not exist :D) .
3) I think that "Fuzzy" means that the translation is a WIP.
4) You're right! Expect an update with working install target and these small fixes in the late afternoon :)
Thanks!

EDIT: pushed right now!

**Comment by FedeDP** [comment]
Closing this one as i added to wiki page "i18n" section, with "how to contribute" explanation.
(https://github.com/FedeDP/ncursesFM/wiki/I18n)
Hope your translation arrives soon :)
